imports:
    - { resource: config.yml }
#    - { resource: assets_version.php }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

#monolog:
#    handlers:
#        main:
#            type:         fingers_crossed
#            action_level: error
#            handler:      nested
#        nested:
#            type:  stream
#            path:  %kernel.logs_dir%/%kernel.environment%.log
#            level: debug

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: notice
            handler: file
        file:
            type: stream
            level: notice
        syslog:
            type: syslog
            level: error
        console:
            type: console
