parameters:

  scan.sitename: scan
  scan.uploadpath:


twig:
    globals:
        order_security_utility: "@order_security_utility"
        scan_sitename: '%scan.sitename%'


services:
    _defaults: { public: true }

    #Custom selector fields
    order_form.type.scan_custom_selector:
        class: Oleg\OrderformBundle\Form\CustomType\ScanCustomSelectorType
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage", "@service_container"]
        tags:
            - { name: form.type, alias: scan_custom_selector }

    #Redirect admin to index
    authentication_handler:
        class: Oleg\OrderformBundle\Security\Authentication\ScanLoginSuccessHandler
        arguments:  ["@service_container", "@doctrine.orm.entity_manager"]

    #security utility
    order_security_utility:
        class: Oleg\OrderformBundle\Security\Util\SecurityUtil
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker", "@service_container"]

    #scanorder utility
    scanorder_utility:
        class: Oleg\OrderformBundle\Helper\OrderUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    #patient utility
    search_utility:
        class: Oleg\OrderformBundle\Helper\SearchUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    scan_role_voter:
        class: Oleg\OrderformBundle\Security\Voter\ScanRoleVoter
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

    scan_permission_voter:
            class: Oleg\OrderformBundle\Security\Voter\ScanPermissionVoter
            arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
            tags:
                - { name: security.voter }
            # small performance boost
            public: false

