#https://symfony.com/bundles/DoctrineMigrationsBundle/2.2.x/index.html
#https://symfony.com/bundles/DoctrineMigrationsBundle/3.3.x/index.html
doctrine_migrations:
    #dir_name: '%kernel.project_dir%/src/Migrations'
    #namespace: DoctrineMigrations

    # List of namespace/path pairs to search for migrations, at least one required
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
        #'AnotherApp\Migrations': '/path/to/other/migrations'
        #'SomeBundle\Migrations': '@SomeBundle/Migrations'

    #table_name: migration_versions
    #column_name: 'version'
    #column_length: 14
    #executed_at_column_name: 'executed_at'
    #name: Application Migrations

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 192
            executed_at_column_name: 'executed_at'

    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    custom_template: ~
    all_or_nothing: true
    #check_database_platform: true



