framework:
    #esi:             ~
#    translator:      { fallback: %locale% }
#    translator: ~
    #translator:
      #enabled: false
#    secret: '%secret%'
    secret: '%env(APP_SECRET)%'
#    router:
#        resource: "%kernel.project_dir%/config/routes.yml"
#        strict_requirements: ~
    form: 
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']        
#        assets_version: SomeVersionScheme
    default_locale:  "%locale%"
#    trusted_proxies: ~
#    session:         ~
#        save_path: ~
    session:
        cookie_lifetime: 0 #Setting a cookie_lifetime to 0 will cause the cookie to live only as long as the browser remains open
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        #http://blog.jmoz.co.uk/symfony2-warning-sessionstart-the-session-id/
        #storage_id: session.storage.filesystem
    #fragments: ~
    fragments: { path: /_fragment }
    http_method_override: true
    profiler:
        collect: false
