parameters:
    webservice_user_provider.class: Oleg\OrderformBundle\Security\User\WebserviceUserProvider

services:

    #custom selector fields
    order_form.type.stain_selector:
        class: Oleg\OrderformBundle\Form\CustomType\CustomSelectorType
        arguments: ["@doctrine.orm.entity_manager","@security.context"]
        tags:
            - { name: form.type, alias: custom_selector }


#    webservice_user_provider:
#            class: "%webservice_user_provider.class%"
#
#    wsse.security.authentication.provider:
#            class:  Oleg\OrderformBundle\Security\Authentication\Provider\WsseProvider
#            arguments: ["", "%kernel.cache_dir%/security/nonces"]
#
#    wsse.security.authentication.listener:
#        class:  Oleg\OrderformBundle\Security\Firewall\WsseListener
#        arguments: ["@security.context", "@security.authentication.manager"]