parameters:

  scan.sitename: scan
  scan.uploadpath:


twig:
    globals:
        order_security_utility: "@order_security_utility"
        scan_sitename: %scan.sitename%


services:

    #Custom selector fields
    order_form.type.custom_selector:
        class: Oleg\OrderformBundle\Form\CustomType\CustomSelectorType
        arguments: ["@doctrine.orm.entity_manager","@security.context", "@service_container"]
        tags:
            - { name: form.type, alias: custom_selector }

    #Redirect admin to index
    authentication_handler:
        class: Oleg\OrderformBundle\Security\Authentication\ScanLoginSuccessHandler
        arguments:  [@service_container, @security.context, @doctrine.orm.entity_manager]

#    #aperio authentication
#    aperio.security.authentication.provider:
#        class: Oleg\OrderformBundle\Security\Authentication\AperioProvider
#        arguments: ["", @service_container,@doctrine.orm.entity_manager,"aperio_ldap_firewall",%default_time_zone%]
#
#    #aperio listener
#    aperio.security.authentication.listener:
#        class: Oleg\OrderformBundle\Security\Firewall\AperioListener
#        arguments: ["@security.context", "@security.authentication.manager", "aperio_ldap_firewall"]

    #security utility
    order_security_utility:
        class: Oleg\OrderformBundle\Security\Util\SecurityUtil
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]

    #scanorder utility
    scanorder_utility:
        class: Oleg\OrderformBundle\Helper\OrderUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@security.context"]

    #patient utility
    search_utility:
        class: Oleg\OrderformBundle\Helper\SearchUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@security.context"]

#    app.patient_hierarchy_voter:
#        class: Oleg\OrderformBundle\Security\Voter\PatientHierarchyVoter
#        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
#        tags:
#            - { name: security.voter }
#        # small performance boost
#        public: false
#
#    app.message_voter:
#            class: Oleg\OrderformBundle\Security\Voter\MessageVoter
#            arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
#            tags:
#                - { name: security.voter }
#            # small performance boost
#            public: false

