parameters:

  fellapp.sitename: fellapp
  fellapp.uploadpath:


twig:
    globals:
        fellapp_sitename: %fellapp.sitename%


services:

    fellapp_authentication_handler:
        class: Oleg\FellAppBundle\Security\Authentication\FellAppLoginSuccessHandler
        arguments:  [@service_container, @security.context, @doctrine.orm.entity_manager]

    #fellowship application utilities
    fellapp_util:
            class: Oleg\FellAppBundle\Util\FellAppUtil
            arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]
    fellapp_importpopulate_util:
        class: Oleg\FellAppBundle\Util\FellAppImportPopulateUtil
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]

    fellapp_reportgenerator:
        class: Oleg\FellAppBundle\Util\ReportGenerator
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container", "@templating"]

    fellapp_googlesheetmanagement:
        class: Oleg\FellAppBundle\Util\GoogleSheetManagement
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]


    fellap_role_voter:
        class: Oleg\FellAppBundle\Security\Voter\FellAppRoleVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    fellap_permission_voter:
        class: Oleg\FellAppBundle\Security\Voter\FellAppPermissionVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }
