# DB and mailer parameters
parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: null
    database_name: scanorder
    database_user: symfony
    database_password: symfony
    database_driver_aperio: pdo_sqlsrv
    database_host_aperio: null
    database_port_aperio: null
    database_name_aperio: null
    database_user_aperio: null
    database_password_aperio: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 563fd817cf2c4f1f692d90650b6fba50f782ccc9
	
#	swift_delivery_addresses is used by delivery_addresses: an array of email addresses where to send ALL emails
    delivery_strategy: realtime
    swift_delivery_addresses:
        - oli2002@med.cornell.edu
