parameters:
  deidentifier.sitename: deidentifier

twig:
    globals:
        deidentifier_sitename: '%deidentifier.sitename%'

services:
    _defaults: { public: true }
#    oleg_deidentifier.example:
#        class: App\DeidentifierBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    deidentifier_authentication_handler:
        class: App\DeidentifierBundle\Security\Authentication\DeidentifierLoginSuccessHandler
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]

    deidentifier_role_voter:
        class: App\DeidentifierBundle\Security\Voter\DeidentifierRoleVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    deidentifier_permission_voter:
        class: App\DeidentifierBundle\Security\Voter\DeidentifierPermissionVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }
