imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@OlegOrderformBundle/Resources/config/services.yml" }
#    - { resource: "@DapsLdapBundle/Resources/config/services.yml"}
#    - { resource: "@OlegOrderformBundle/Resources/config/fr3dlap_service.xml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator: ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: 
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
#        save_path: ~
    fragments:       ~

# Twig Configuration
twig:
    form:
      resources: ['form_div_layout.html.twig']
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
#    form:
#      resources: ['form_table_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['OlegOrderformBundle']
    #java: /usr/bin/java
    filters:
         less:
              node: /usr/local/bin/node
              node_paths: [/usr/local/lib/node_modules]
              apply_to: "\.less$"
         cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
#    read_from: "%kernel.root_dir%/../../../../order"
#    read_from: "%kernel.root_dir%/../../.."

#bootstrap assets; maybe I don't need it
#    assets:
#          img_bootstrap_glyphicons_eot:
#              inputs:
#                -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/bootstrap/fonts/glyphicons-halflings-regular.eot"
#              output: "fonts/glyphicons-halflings-regular.eot"
#          img_bootstrap_glyphicons_woff:
#              inputs:
#                -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/bootstrap/fonts/glyphicons-halflings-regular.woff"
#              output: "fonts/glyphicons-halflings-regular.woff"
#          img_bootstrap_glyphicons_svg:
#              inputs:
#                -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/bootstrap/fonts/glyphicons-halflings-regular.svg"
#              output: "fonts/glyphicons-halflings-regular.svg"
#          img_bootstrap_glyphicons_ttf:
#              inputs:
#                -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/bootstrap/fonts/glyphicons-halflings-regular.ttf"
#              output: "fonts/glyphicons-halflings-regular.ttf"
#          img_select2:
#              inputs:
#                -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/select2/select2.png"
#              output: "css/select2.png"

#          img_bootstrap_glyphicons_black:
#              inputs:
#                -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/bootstrap/img/glyphicons-halflings.png"
#              output: "img/glyphicons-halflings.png"
#          css_bootstrap:
#              inputs:
#                  -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/bootstrap/css/*"
#              output: "css/bootstrap.css"
#            js_bootstrap:
#                inputs:
#                    -  "%kernel.root_dir%/../src/Oleg/OrderformBundle/Resources/public/bootstrap/js/*.js"
#                output: "js/bootstrap.js"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

