imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        #storage_id: session.storage.filesystem
    profiler:
        enabled: false
    router:
        resource: "%kernel.project_dir%/app/config/routing_test.yml"
        strict_requirements: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
