security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#        Oleg\OrderformBundle\Security\User\WebserviceUser: sha512
#        Oleg\OrderformBundle\Security\User\WebserviceUser: plaintext
#        Daps\LdapBundle\Security\User\LdapUser: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
#        Ztec\Security\ActiveDirectoryBundle\Security\User\adUser : plaintext #Active directory does not support encrypted password yet

    role_hierarchy:

        ROLE_ALL_SUBMITTER: [ROLE_SUBMITTER, ROLE_EXTERNAL_SUBMITTER]
        ROLE_ALL_ORDERING_PROVIDER: [ROLE_ORDERING_PROVIDER, ROLE_EXTERNAL_ORDERING_PROVIDER]
        ROLE_ALL_PATHOLOGY: [ROLE_PATHOLOGY_RESIDENT, ROLE_PATHOLOGY_FELLOW, ROLE_PATHOLOGY_FACULTY]

        ROLE_PROCESSOR:    [ROLE_ALL_SUBMITTER,ROLE_ALL_ORDERING_PROVIDER,ROLE_ALL_PATHOLOGY]
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_ALL_SUBMITTER, ROLE_ALL_ORDERING_PROVIDER, ROLE_ALL_PATHOLOGY]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:

        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fos_userbundle:
            id: fos_user.user_provider.username
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        aperioauth:
            id: aperio_authenticator

#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass123, roles: [ 'ROLE_ADMIN' ] }

    firewalls:

        secured_area:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                 always_use_default_target_path: false
                 provider: chain_provider
                 use_referer: true
                 success_handler: login_sucess_handler
            simple-form:
                 always_use_default_target_path: false
                 provider:      aperioauth
                 authenticator: aperio_authenticator
                 use_referer: true
            logout:
                path:   /logout
                target: /login
            anonymous:  true
          
    access_control:
     - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/admin/, role: ROLE_ADMIN }
     - { path: ^/util/, role: [ROLE_SUBMITTER, ROLE_EXTERNAL_SUBMITTER] }
     - { path: ^/user/, role: ROLE_USER }
     - { path: ^/check/, role: [ROLE_SUBMITTER, ROLE_EXTERNAL_SUBMITTER] }
     - { path: ^/index, role: [ROLE_SUBMITTER, ROLE_EXTERNAL_SUBMITTER, ROLE_ORDERING_PROVIDER, ROLE_EXTERNAL_ORDERING_PROVIDER]}


