security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:

        ROLE_SCANORDER_ALL_SUBMITTER: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_EXTERNAL_SUBMITTER]
        ROLE_SCANORDER_ALL_ORDERING_PROVIDER: [ROLE_SCANORDER_ORDERING_PROVIDER, ROLE_SCANORDER_EXTERNAL_ORDERING_PROVIDER]
        ROLE_SCANORDER_ALL_PATHOLOGY: [ROLE_SCANORDER_PATHOLOGY_RESIDENT, ROLE_SCANORDER_PATHOLOGY_FELLOW, ROLE_SCANORDER_PATHOLOGY_FACULTY]

        ROLE_SCANORDER_PATHOLOGY_RESIDENT: [ROLE_SCANORDER_ALL_SUBMITTER, ROLE_SCANORDER_ALL_ORDERING_PROVIDER]
        ROLE_SCANORDER_PATHOLOGY_FELLOW: [ROLE_SCANORDER_ALL_SUBMITTER, ROLE_SCANORDER_ALL_ORDERING_PROVIDER]
        ROLE_SCANORDER_PATHOLOGY_FACULTY: [ROLE_SCANORDER_ALL_SUBMITTER, ROLE_SCANORDER_ALL_ORDERING_PROVIDER]

        ROLE_SCANORDER_PROCESSOR:   [ROLE_SCANORDER_ALL_SUBMITTER,ROLE_SCANORDER_ALL_ORDERING_PROVIDER,ROLE_SCANORDER_ALL_PATHOLOGY]
        ROLE_SCANORDER_ADMIN:       [ROLE_ADMIN, ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_SCANORDER_PROCESSOR, ROLE_SCANORDER_ALL_SUBMITTER, ROLE_SCANORDER_ALL_ORDERING_PROVIDER, ROLE_SCANORDER_ALL_PATHOLOGY]
        ROLE_SCANORDER_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_USER, ROLE_SCANORDER_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:

        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fos_userbundle:
            id: fos_user.user_provider.username

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider


    #        in_memory:
    #            memory:
    #                users:
    #                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #                    admin: { password: adminpass123, roles: [ 'ROLE_SCANORDER_ADMIN' ] }

    firewalls:

        #this firewall name must be the same as in the bundle's service.yml.
        aperio_ldap_firewall:

            pattern: ^/

            aperio: true

            fr3d_ldap:  ~

            form_login:
                 always_use_default_target_path: false
                 use_referer: true
                 success_handler: authentication_handler
                 failure_handler: authentication_handler

            logout:
                path:   /logout
                target: /login

            anonymous:  true

            access_denied_url: /scan/scan-order/no-permission

          
    access_control:

     - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/scan/access-requests/, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/scan/account-requests/, role: IS_AUTHENTICATED_ANONYMOUSLY }

     - { path: ^/scan/admin/genall, role: ROLE_SCANORDER_ADMIN }
     - { path: ^/scan/users/generate, role: ROLE_SCANORDER_ADMIN }
     - { path: ^/scan/users/new, role: ROLE_SCANORDER_ADMIN }
     - { path: ^/scan/user-directory, role: ROLE_SCANORDER_PROCESSOR }

     - { path: ^/scan/admin/, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/incoming-scan-orders, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/settings/, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/incoming-scan-orders, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/access-requests, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/account-requests, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/event-log, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/incoming-slide-return-requests, role: [ROLE_SCANORDER_PROCESSOR]}

     - { path: ^/scan/util/pathservice, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/scan/util/, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_EXTERNAL_SUBMITTER] }
     - { path: ^/scan/check/, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_EXTERNAL_SUBMITTER] }

     - { path: ^/scan/users/, role: ROLE_USER }
     - { path: ^/scan/edit-user-profile/, role: [ROLE_USER] }

     - { path: ^/scan/scan-order, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_EXTERNAL_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER, ROLE_SCANORDER_EXTERNAL_ORDERING_PROVIDER]}
     - { path: ^/scan/my-scan-orders, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_EXTERNAL_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER, ROLE_SCANORDER_EXTERNAL_ORDERING_PROVIDER]}

     - { path: ^/scan/slide-return-request, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_EXTERNAL_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER, ROLE_SCANORDER_EXTERNAL_ORDERING_PROVIDER]}
     - { path: ^/scan/my-slide-return-requests, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_EXTERNAL_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER, ROLE_SCANORDER_EXTERNAL_ORDERING_PROVIDER]}

