security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#        Oleg\OrderformBundle\Security\User\WebserviceUser: sha512
#        Oleg\OrderformBundle\Security\User\WebserviceUser: plaintext
        Daps\LdapBundle\Security\User\LdapUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        Oleg: custom user
#        webservice:
#            id: webservice_user_provider
        daps_ldap:
            id: daps_ldap_user_provider
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false
#            pattern:  ^/login$
#            security: true

        login_firewall:
            pattern:    ^/login$
            anonymous:  ~

        #Oleg: custom auth provider
#        wsse_secured:
#            pattern:   ^/
#            stateless: true
#            wsse:      true            
#            form_login:              
#                login_path:  login
#                check_path:  login_check

        secured_area:
            pattern:    ^/
#            anonymous: ~           
            form-login-ldap: true           
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   /logout/
                target: orderinfo

#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
