security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:

        ROLE_SCANORDER_ALL_PATHOLOGY: [ROLE_SCANORDER_PATHOLOGY_RESIDENT, ROLE_SCANORDER_PATHOLOGY_FELLOW, ROLE_SCANORDER_PATHOLOGY_FACULTY]

        ROLE_SCANORDER_PATHOLOGY_RESIDENT: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER]
        ROLE_SCANORDER_PATHOLOGY_FELLOW: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER]
        ROLE_SCANORDER_PATHOLOGY_FACULTY: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER]

        ROLE_SCANORDER_PROCESSOR:   [ROLE_SCANORDER_SUBMITTER,ROLE_SCANORDER_ORDERING_PROVIDER,ROLE_SCANORDER_ALL_PATHOLOGY]
        ROLE_SCANORDER_ADMIN:       [ROLE_ADMIN, ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_SCANORDER_PROCESSOR, ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER, ROLE_SCANORDER_ALL_PATHOLOGY]
        ROLE_SCANORDER_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_USER, ROLE_SCANORDER_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        ROLE_USERDIRECTORY_ADMIN:   [ROLE_USER, ROLE_ADMIN]


    providers:

        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fos_userbundle:
            id: fos_user.user_provider.username

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

    #        in_memory:
    #            memory:
    #                users:
    #                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #                    admin: { password: adminpass123, roles: [ 'ROLE_SCANORDER_ADMIN' ] }

    firewalls:

        #this firewall name must be the same as in the bundle's service.yml.
        aperio_ldap_firewall:

            pattern: ^/scan

            aperio: true

            fr3d_ldap:  ~

            context: scan_auth

            form_login:
                 always_use_default_target_path: false
                 use_referer: true
                 success_handler: authentication_handler
                 failure_handler: authentication_handler
                 check_path: /scan/login_check
                 login_path: /scan/login

            logout:
                path:   /scan/logout
                target: /scan/login

            anonymous:  true

            access_denied_url: /scan/scan-order/no-permission


        ldap_employees_firewall:
            pattern: ^/employees
            aperio: true
            context: employees_auth
            form_login:
                check_path: /employees/login_check
                login_path: /employees/login
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /employees/admin
                target_path_parameter:          _target_path
                use_referer:                    false
            logout:
                path:   /employees/logout
                target: /employees/login
            anonymous:  true

          
    access_control:

     - { path: ^/employees/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/employees/admin, role: ROLE_USERDIRECTORY_ADMIN }

     - { path: ^/scan/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/scan/access-requests/, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/scan/account-requests/, role: IS_AUTHENTICATED_ANONYMOUSLY }

     - { path: ^/scan/admin/genall, role: ROLE_SCANORDER_ADMIN }
     - { path: ^/scan/users/generate, role: ROLE_SCANORDER_ADMIN }
     - { path: ^/scan/users/new, role: ROLE_SCANORDER_ADMIN }
     - { path: ^/scan/user-directory, role: ROLE_SCANORDER_PROCESSOR }

     - { path: ^/scan/admin/, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/incoming-scan-orders, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/settings/, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/incoming-scan-orders, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/access-requests, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/account-requests, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/event-log, role: ROLE_SCANORDER_PROCESSOR }
     - { path: ^/scan/incoming-slide-return-requests, role: [ROLE_SCANORDER_PROCESSOR]}

     - { path: ^/scan/util/pathservice, role: IS_AUTHENTICATED_ANONYMOUSLY }
     - { path: ^/scan/util/, role: [ROLE_SCANORDER_SUBMITTER] }
     - { path: ^/scan/check/, role: [ROLE_SCANORDER_SUBMITTER] }

     - { path: ^/scan/users/, role: ROLE_USER }
     - { path: ^/scan/edit-user-profile/, role: [ROLE_USER] }

     - { path: ^/scan/scan-order, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER]}
     - { path: ^/scan/my-scan-orders, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER]}

     - { path: ^/scan/slide-return-request, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER]}
     - { path: ^/scan/my-slide-return-requests, role: [ROLE_SCANORDER_SUBMITTER, ROLE_SCANORDER_ORDERING_PROVIDER]}

