security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#        Oleg\OrderformBundle\Security\User\WebserviceUser: sha512
#        Oleg\OrderformBundle\Security\User\WebserviceUser: plaintext
#        Daps\LdapBundle\Security\User\LdapUser: plaintext
#        Ztec\Security\ActiveDirectoryBundle\Security\User\adUser : plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        Oleg: custom user
#        webservice:
#            id: webservice_user_provider
#        daps_ldap:
#            id: daps_ldap_user_provider   
#        ldap:
#            id: imag_ldap.security.user.provider
#        my_active_directory_provider:
#            id: ztec.security.active.directory.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username 
            
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#            pattern:  ^/login$
#            security: true           

#        login_firewall:
#            pattern:    ^/login$
#            anonymous:  ~          

        #Oleg: custom auth provider
#        wsse_secured:
#            pattern:   ^/
#            stateless: true
#            wsse:      true            
#            form_login:              
#                login_path:  login
#                check_path:  login_check
#        public:
#            pattern: /order/          
#            anonymous:  ~
    
#        secured_area:
##            active_directory: #Sames parameters as form_login
##                check_path: login_check
##                login_path: login
#          
#            pattern:    ^/
##            anonymous: ~           
###            form-login-ldap: true             
#            form_login:
#                login_path:  login
#                check_path:  login_check
###                always_use_default_target_path: true                             
#            logout:
#                path:   /logout/
#                target: /

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

#    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }