parameters:
    daps_ldap.ldap.admin.dn: cn=a,dc=wcmc-ad,dc=net
    daps_ldap.ldap.admin.password: Aperi0,123
    daps_ldap.ldap.admin.enable: true
    daps_ldap.ldap.host: a.wcmc-ad.net
    daps_ldap.ldap.port: 389
    daps_ldap.ldap.dn: uid
    daps_ldap.ldap.username_suffix: dc=wcmc-ad,dc=net
