parameters:

  employees.sitename: employees
  employees.uploadpath:
  employees.avataruploadpath:

  default_time_zone: America/New_York
  default_system_email:
  institution_url:
  institution_name:
  department_url:
  department_name:

  #ldap
  ldaphost: cumcdcp02.a.wcmc-ad.net
  ldapport: 389
  ldapou: a.wcmc-ad.net
  ldapusername: svc_aperio_spectrum
  ldappassword: Aperi0,123
  ldapexepath: ../src/Oleg/UserdirectoryBundle/Util/
  ldapexefilename: LdapSaslCustom.exe

  #titles
  mainhome_title:
  listmanager_title:
  eventlog_title:
  sitesettings_title:
  contentabout_page:

#  maintenance:
#  maintenanceenddate:
#  maintenanceloginmsg:
#  maintenancelogoutmsg:

#framework:
#    session:
#        cookie_lifetime: 20
#        gc_maxlifetime: 10


#original
#fr3d_ldap:
#
#    driver:
#        host: a.wcmc-ad.net
#        username: svc_aperio_spectrum@a.wcmc-ad.net
#        password: Aperi0,123
#        accountDomainName: a.wcmc-ad.net
##       host:              a.wcmc-ad.net                            # Required
##       username:          svc_aperio_spectrum@a.wcmc-ad.net        # Optional
##       password:          Aperi0,123                               # Optional
##       accountDomainName: a.wcmc-ad.net                            # Required
#    user:
#        baseDn: dc=a,dc=wcmc-ad,dc=net
#        filter: (&(ObjectClass=Person)) #Person
#        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
#                - { ldap_attr: cn,   user_method: setUsername }
#                - { ldap_attr: mail,   user_method: setEmail }
#                - { ldap_attr: sn,   user_method: setLastName }
#                - { ldap_attr: title,   user_method: setTitle }
#                - { ldap_attr: givenname,   user_method: setFirstName }
#                - { ldap_attr: displayname,   user_method: setDisplayName }
#    service:
#        ldap_manager:  oleg.security.ldap_manager

#experimental
#fr3d_ldap:
#    driver:
#        host: cumcdcp02.a.wcmc-ad.net
#        username: svc_aperio_spectrum
#        password: Aperi0,123
#        accountDomainName: a.wcmc-ad.net
#        optReferrals: 0  # Optional
#    user:
#        baseDn: CN=Users,DC=a,DC=wcmc-ad,DC=net
#        filter: (&(ObjectClass=user))
#        #filter: (&(cn=%s))
#        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
#                - { ldap_attr: cn,   user_method: setUsername }
#                - { ldap_attr: mail,   user_method: setEmail }
#                - { ldap_attr: title,   user_method: setTitle }
#                - { ldap_attr: sn,   user_method: setLastName }
#                - { ldap_attr: givenname,   user_method: setFirstName }
#                - { ldap_attr: displayname,   user_method: setDisplayName }
#    service:
#        ldap_manager:  oleg.security.ldap_manager


#fos user bundle
fos_user:
    db_driver: orm
#    model_manager_name: default
    firewall_name: main
    user_class: Oleg\UserdirectoryBundle\Entity\User


services:

    custom_authenticator:
        class:     Oleg\UserdirectoryBundle\Security\Authentication\CustomAuthenticator
        arguments: ["@security.password_encoder",@service_container,@doctrine.orm.entity_manager]

    oleg.listener.maintenance:
        class: Oleg\UserdirectoryBundle\Services\MaintenanceListener
        arguments: ["@service_container","@doctrine.orm.entity_manager","@security.context"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    #Custom selector fields
    oleg.type.employees_custom_selector:
        class: Oleg\UserdirectoryBundle\Form\CustomType\CustomSelectorType
        arguments: ["@doctrine.orm.entity_manager","@security.context", "@service_container"]
        tags:
            - { name: form.type, alias: employees_custom_selector }

    #idle time out handler (can pass %session_max_idle_time%. Now use DB)
    oleg.handler.session_idle:
        class: Oleg\UserdirectoryBundle\Services\SessionIdleHandler
        arguments: ["@session", "@security.context", "@router", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    #Override Ldap Manager
#    oleg.security.ldap_manager:
#        class: Oleg\UserdirectoryBundle\Security\Authentication\LdapManager
#        arguments: [@fr3d_ldap.ldap_driver, @fr3d_ldap.user_manager, %fr3d_ldap.ldap_manager.parameters%, @service_container, @doctrine.orm.entity_manager ]

    #Redirect admin to index
    employees_authentication_handler:
        class: Oleg\UserdirectoryBundle\Security\Authentication\LoginSuccessHandler
        arguments:  [@service_container, @security.context, @doctrine.orm.entity_manager]

    #twig listener
    twigdate.listener.request:
        class: Oleg\UserdirectoryBundle\Services\TwigDateRequestListener
        arguments: ["@twig", "@security.context", %default_time_zone%]
        tags:
              - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    #user security util
    user_security_utility:
        class: Oleg\UserdirectoryBundle\Security\Util\UserSecurityUtil
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]

    #OneupUploaderBundle upload listener
    oleg.upload_listener:
        class: Oleg\UserdirectoryBundle\Services\UploadListener
        arguments: [@service_container,@doctrine.orm.entity_manager,@security.context]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
#            - { name: kernel.event_listener, event: oneup_uploader.pre_upload, method: preUpload }

    #Doctrine listenere for postPersist
    doctrine.listener:
        class: Oleg\UserdirectoryBundle\Services\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: postPersist, connection: default }


