parameters:

#  default_time_zone: America/New_York
#  default_system_email:
#  institution_url:
#  institution_name:
#  department_url:
#  department_name:

#  maintenance:
#  maintenanceenddate:
#  maintenanceloginmsg:
#  maintenancelogoutmsg:


#framework:
#    session:
#        cookie_lifetime: 20
#        gc_maxlifetime: 10

fr3d_ldap:
    driver:
        host: a.wcmc-ad.net
        username: svc_aperio_spectrum@a.wcmc-ad.net
        password: Aperi0,123
        accountDomainName: a.wcmc-ad.net
#       host:              a.wcmc-ad.net                            # Required
#       username:          svc_aperio_spectrum@a.wcmc-ad.net        # Optional
#       password:          Aperi0,123                               # Optional
#       accountDomainName: a.wcmc-ad.net                            # Required
    user:
        baseDn: dc=a,dc=wcmc-ad,dc=net
        filter: (&(ObjectClass=user))
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
                - { ldap_attr: cn,   user_method: setUsername }
                - { ldap_attr: mail,   user_method: setEmail }
                - { ldap_attr: sn,   user_method: setLastName }
                - { ldap_attr: title,   user_method: setTitle }
                - { ldap_attr: givenname,   user_method: setFirstName }
                - { ldap_attr: displayname,   user_method: setDisplayName }
    service:
        ldap_manager:  oleg.security.ldap_manager


#fos user bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Oleg\UserdirectoryBundle\Entity\User

services:

#    #Custom selector fields
#    order_form.type.stain_selector:
#        class: Oleg\OrderformBundle\Form\CustomType\CustomSelectorType
#        arguments: ["@doctrine.orm.entity_manager","@security.context", "@service_container"]
#        tags:
#            - { name: form.type, alias: custom_selector }
#
#    #Custom selector fields with data
#    order_form.type.custom_data_selector:
#        class: Oleg\OrderformBundle\Form\CustomType\CustomDataSelectorType
#        arguments: ["@doctrine.orm.entity_manager","@security.context", "@service_container"]
#        tags:
#            - { name: form.type, alias: custom_data_selector }
#
#    #Redirect admin to index
#    authentication_handler:
#        class: Oleg\OrderformBundle\Security\Authentication\LoginSuccessHandler
#        arguments:  [@router, @security.context, @doctrine.orm.entity_manager]

    #Override Ldap Manager
    oleg.security.ldap_manager:
        class: Oleg\UserdirectoryBundle\Security\Authentication\LdapManager
        arguments: [@fr3d_ldap.ldap_driver, @fr3d_ldap.user_manager, %fr3d_ldap.ldap_manager.parameters%, %default_time_zone%, @doctrine.orm.entity_manager ]

#    #idle time out handler (can pass %session_max_idle_time%. Now use DB)
#    oleg.handler.session_idle:
#        class: Oleg\OrderformBundle\Helper\SessionIdleHandler
#        arguments: ["@session", "@security.context", "@router", "@doctrine.orm.entity_manager"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    #Redirect admin to index
    employees_authentication_handler:
        class: Oleg\UserdirectoryBundle\Security\Authentication\LoginSuccessHandler
        arguments:  [@service_container, @security.context, @doctrine.orm.entity_manager]

    #twig listener
    twigdate.listener.request:
        class: Oleg\UserdirectoryBundle\Services\TwigDateRequestListener
        arguments: ["@twig", "@security.context", %default_time_zone%]
        tags:
              - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    #user security util
    user_security_utility:
        class: Oleg\UserdirectoryBundle\Security\Util\UserSecurityUtil
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@service_container"]
