parameters:

    translationalresearch.sitename: translationalresearch
    translationalresearch.uploadpath:


twig:
    globals:
        translationalresearch_sitename: '%translationalresearch.sitename%'
        #service
#        translationalresearch_util: "@translationalresearch_util"


services:

    translationalresearch_authentication_handler:
        class: Oleg\TranslationalResearchBundle\Security\Authentication\TranslationalResearchLoginSuccessHandler
        arguments:  ["@service_container", "@doctrine.orm.entity_manager"]

    translationalresearch_role_voter:
        class: Oleg\TranslationalResearchBundle\Security\Voter\TranslationalResearchRoleVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    translationalresearch_permission_voter:
        class: Oleg\TranslationalResearchBundle\Security\Voter\TranslationalResearchPermissionVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    transres_util:
        class: Oleg\TranslationalResearchBundle\Util\TransResUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]


framework:
    workflows:
        transres_project:
            type: 'state_machine'
            marking_store:
                type: 'single_state' # 'multiple_state' or 'single_state'
                arguments:
                    - 'state' #state keeps the marking state
            supports:
                - Oleg\TranslationalResearchBundle\Entity\Project
            #Project has state which is equal to this place
            places:
                - start
                - draft
                - complete
                - irb_review      #available for IRB review
                - irb_rejected    #rejected by IRB review. User can re-submit the project -resubmit_irb_rejected-> irb_review
                - admin_review
                - admin_rejected
                - committee_review
                - committee_rejected
                - final_review
                - approved
                - not_approved
                - closed
            transitions:
                draft:
                    from: start
                    to: draft
                #Complete submittion
                submit:
                    from: [start, draft]
                    to: complete
                ### Re-submit after rejected ###
                resubmit_irb_rejected:
                   from: irb_rejected
                   to: irb_review
                resubmit_admin_rejected:
                   from: admin_rejected
                   to: admin_review
                resubmit_committee_rejected:
                   from: committee_rejected
                   to: committee_review

                ### Main Actions ###
                #IRB Review
                to_irb_review:
                    from: complete
                    to: irb_review
                irb_review_no:
                    from: irb_review
                    to: irb_rejected
                #ADMIN Review
                to_admin_review:
                    from: irb_review
                    to: admin_review
                admin_review_no:
                    from: admin_review
                    to: admin_rejected
                #COMMITTEE Review
                to_committee_review:
                    from: admin_review
                    to: committee_review
                committee_review_no:
                    from: committee_review
                    to: committee_rejected
                #FINAL Review
                to_final_review:
                    from: committee_review
                    to: final_review
                final_review_yes:
                    from: final_review
                    to: approved
                final_review_no:
                    from: final_review
                    to: not_approved
                #Closed
                approved_closed:
                    from: approved
                    to: closed
                #Un-Closed
                closed_approved:
                    from: closed
                    to: approved