parameters:

    translationalresearch.sitename: translationalresearch
    transres.uploadpath:


twig:
    globals:
        translationalresearch_sitename: '%translationalresearch.sitename%'
        #service
#        translationalresearch_util: "@translationalresearch_util"


services:

    translationalresearch_authentication_handler:
        class: Oleg\TranslationalResearchBundle\Security\Authentication\TranslationalResearchLoginSuccessHandler
        arguments:  ["@service_container", "@doctrine.orm.entity_manager"]

    translationalresearch_role_voter:
        class: Oleg\TranslationalResearchBundle\Security\Voter\TranslationalResearchRoleVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    translationalresearch_permission_voter:
        class: Oleg\TranslationalResearchBundle\Security\Voter\TranslationalResearchPermissionVoter
        public: false
        arguments: ['@security.access.decision_manager', "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: security.voter }

    transres_util:
        class: Oleg\TranslationalResearchBundle\Util\TransResUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    transres_request_util:
        class: Oleg\TranslationalResearchBundle\Util\TransResRequestUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    transres_formnode_util:
        class: Oleg\TranslationalResearchBundle\Util\TransResFormNodeUtil
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    transres_pdf_generator:
        class: Oleg\TranslationalResearchBundle\Util\PdfGenerator
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]


framework:
    workflows:
        transres_project:
            type: 'state_machine'
            marking_store:
                type: 'single_state' # 'multiple_state' or 'single_state'
                arguments:
                    - 'state' #state keeps the marking state
            supports:
                - Oleg\TranslationalResearchBundle\Entity\Project
            #Project has state which is equal to this place
            places:
                - start
                - draft
#                - completed
                # irb
                - irb_review        #available for IRB review
#                - irb_approved     #approved by IRB review. Project goes to the next stage
                - irb_rejected      #rejected by IRB review. User can re-submit the project -resubmit_irb_rejected-> irb_review
                - irb_missinginfo   #Pending additional information from submitter - Request additional information from submitter
                # admin
                - admin_review
#                - admin_approved
                - admin_rejected
                - admin_missinginfo
                # committee
                - committee_review
#                - committee_approved
                - committee_rejected
#                - committee_missinginfo
                # final
                - final_review
                - final_approved
                - final_rejected
#                - final_missinginfo
                # closed
                - closed

            transitions:
                to_draft:
                    from: start
                    to: draft
#                to_completed:
#                    from: [start, draft]
#                    to: completed
                to_review:
                    from: [start, draft]
                    to: irb_review

                ### Main Actions ###
                #IRB Review
                irb_review_approved:
                    from: irb_review
                    to: admin_review
                irb_review_rejected:
                    from: irb_review
                    to: irb_rejected
                irb_review_missinginfo:
                    from: irb_review
                    to: irb_missinginfo
                irb_review_resubmit:
                     from: irb_missinginfo
                     to: irb_review
                #ADMIN Review
                admin_review_approved:
                    from: admin_review
                    to: committee_review
                admin_review_rejected:
                    from: admin_review
                    to: admin_rejected
                admin_review_missinginfo:
                    from: admin_review
                    to: admin_missinginfo
                admin_review_resubmit:
                     from: admin_missinginfo
                     to: admin_review
                #COMMITTEE Review
                committee_review_approved:
                    from: committee_review
                    to: final_review
                committee_review_rejected:
                    from: committee_review
                    to: committee_rejected
#                committee_review_missinginfo:
#                    from: committee_review
#                    to: committee_missinginfo
#                committee_review_resubmit:
#                    from: committee_missinginfo
#                    to: committee_review

                committee_finalreview_approved:
                    from: committee_review
                    to: final_approved

                #FINAL Review
                final_review_approved:
                    from: final_review
                    to: final_approved
                final_review_rejected:
                    from: final_review
                    to: final_rejected
#                final_review_missinginfo:
#                    from: final_review
#                    to: final_missinginfo
#                final_review_resubmit:
#                     from: final_missinginfo
#                     to: final_review

                #Closed
                approved_closed:
                    from: final_approved
                    to: closed
                #Un-Closed
                closed_approved:
                    from: closed
                    to: final_approved

        transres_request_billing:
            type: 'state_machine'
            marking_store:
                type: 'single_state' # 'multiple_state' or 'single_state'
                arguments:
                    - 'billingState' #state keeps the marking state
            supports:
                - Oleg\TranslationalResearchBundle\Entity\TransResRequest
            places:
                - draft
                - active
                - approvedInvoicing
                - canceled
                - missinginfo
                - invoiced
                - paid
                - refunded
                - partiallyRefunded
            transitions:
                draft_active:
                    from: draft
                    to: active
                active_canceled:
                    from: active
                    to: canceled
                canceled_active:
                    from: canceled
                    to: active
                active_approvedInvoicing:
                    from: active
                    to: approvedInvoicing
                approvedInvoicing_active:
                    from: approvedInvoicing
                    to: active
                approvedInvoicing_canceled:
                    from: approvedInvoicing
                    to: canceled
                missinginfo_approvedInvoicing:
                    from: missinginfo
                    to: approvedInvoicing
                approvedInvoicing_invoiced:
                    from: approvedInvoicing
                    to: invoiced
                approvedInvoicing_missinginfo:
                    from: approvedInvoicing
                    to: missinginfo
                invoiced_paid:
                    from: invoiced
                    to: paid
                invoiced_refunded:
                    from: invoiced
                    to: refunded
                invoiced_canceled:
                    from: invoiced
                    to: canceled
                invoiced_approvedInvoicing:
                    from: invoiced
                    to: approvedInvoicing
                invoiced_partiallyRefunded:
                     from: invoiced
                     to: partiallyRefunded
                paid_refunded:
                    from: paid
                    to: refunded
                #Add arrows from "Paid", "Refunded", and "Partially Refunded" to "Canceled" and to "Invoiced" (6 new arrows total)
                paid_canceled:
                    from: paid
                    to: canceled
                refunded_canceled:
                    from: refunded
                    to: canceled
                partiallyRefunded_canceled:
                    from: partiallyRefunded
                    to: canceled
                paid_invoiced:
                    from: paid
                    to: invoiced
                refunded_invoiced:
                    from: refunded
                    to: invoiced
                partiallyRefunded_invoiced:
                    from: partiallyRefunded
                    to: invoiced

        transres_request_progress:
            type: 'state_machine'
            marking_store:
                type: 'single_state' # 'multiple_state' or 'single_state'
                arguments:
                    - 'progressState' #state keeps the marking state
            supports:
                - Oleg\TranslationalResearchBundle\Entity\TransResRequest
            places:
                - draft
                - active
                - canceled
                - investigator
                - histo
                - ihc
                - mol
                - retrieval
                - payment
                - slidescanning
                - block
                - other
                - suspended
                - completed
                - completedNotified
            transitions:
                draft_active:
                    from: draft
                    to: active
                active_canceled:
                    from: active
                    to: canceled
                canceled_active:
                    from: canceled
                    to: active
                canceled_completed:
                    from: canceled
                    to: completed
                active_completed:
                    from: active
                    to: completed
                completed_active:
                    from: completed
                    to: active
                completed_canceled:
                    from: completed
                    to: canceled
                completed_completedNotified:
                    from: completed
                    to: completedNotified
                completedNotified_completed:
                    from: completedNotified
                    to: completed
                completedNotified_canceled:
                    from: completedNotified
                    to: canceled
                canceled_completedNotified:
                    from: canceled
                    to: completedNotified
                completedNotified_active:
                    from: completedNotified
                    to: active
                active_completedNotified:
                    from: active
                    to: completedNotified

                #active to pending
                active_investigator:
                    from: active
                    to: investigator
                active_histo:
                    from: active
                    to: histo
                active_ihc:
                    from: active
                    to: ihc
                active_mol:
                    from: active
                    to: mol
                active_retrieval:
                    from: active
                    to: retrieval
                active_payment:
                    from: active
                    to: payment
                active_slidescanning:
                    from: active
                    to: slidescanning
                active_block:
                    from: active
                    to: block
                active_suspended:
                    from: active
                    to: suspended
                active_other:
                    from: active
                    to: other
                #pending to completed
                investigator_completed:
                    from: investigator
                    to: completed
                histo_completed:
                    from: histo
                    to: completed
                ihc_completed:
                    from: ihc
                    to: completed
                mol_completed:
                    from: mol
                    to: completed
                retrieval_completed:
                    from: retrieval
                    to: completed
                payment_completed:
                    from: payment
                    to: completed
                slidescanning_completed:
                    from: slidescanning
                    to: completed
                block_completed:
                    from: block
                    to: completed
                suspended_completed:
                    from: suspended
                    to: completed
                other_completed:
                    from: other
                    to: completed
                #completed to all other statuses EXCEPT Draft
                completed_investigator:
                    from: completed
                    to: investigator
                completed_histo:
                    from: completed
                    to: histo
                completed_ihc:
                    from: completed
                    to: ihc
                completed_mol:
                    from: completed
                    to: mol
                completed_retrieval:
                    from: completed
                    to: retrieval
                completed_payment:
                    from: completed
                    to: payment
                completed_slidescanning:
                    from: completed
                    to: slidescanning
                completed_block:
                    from: completed
                    to: block
                completed_suspended:
                    from: completed
                    to: suspended
                completed_other:
                    from: completed
                    to: other
